model_reasoning_effort = "xhigh"
model = "gpt-5.4"

[projects."/Users/zpp/Desktop/gitlab/cnstrong-WebRTC"]
trust_level = "trusted"

[projects."/Users/zpp"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.-]
url = "https://anycross.feishu.cn/mcp/openplatform_query/stream?key=nZ7yDqc1_fg6hSBAGJypqmUnCAgWNHIiqwYZ2qGjfmZ4kJfBmqGt_riGvR0n9ZLP"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.apifox_user_api]
args = ["-y", "apifox-mcp-server@latest", "--project-id=7930557"]
command = "npx"
enabled = true

[mcp_servers.apifox_user_api.env]
APIFOX_ACCESS_TOKEN = "afxp_8dc548PQmlpruCsbLKacOfccXIwXdQQqvViD"
